---
name: Build for MacOS

on:
  workflow_dispatch:
    inputs:
      git_tag:
        description: "Git tag to build (e.g. v2.52.0)"
        required: true
        default: master

env:
  GIT_TAG: ${{ github.event.inputs.git_tag }}

jobs:
  build:
    name: Build tag ${{ github.event.inputs.git_tag }}
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GIT_TAG }}
          fetch-depth: 0

      - name: Dependencies
        run: brew install autoconf automake libtool gettext openssl@3 curl expat

      - name: Build
        run: |
          export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
          export OPENSSL_PATH=$(brew --prefix openssl@3)
          export CURL_PATH=$(brew --prefix curl)
          export EXPAT_PATH=$(brew --prefix expat)

          make configure
          ./configure --prefix=$HOME/git-portable \
                      --with-openssl=$OPENSSL_PATH \
                      --with-curl=$CURL_PATH \
                      --with-expat=$EXPAT_PATH \
                      --without-tcltk \
                      CC=gcc

          make -j$(sysctl -n hw.ncpu)
          make install

      - name: Extract Version
        id: get_version
        run: |
          RAW_VERSION=$(cat GIT-VERSION-FILE | cut -d' ' -f3 | tr -d '\n')
          CLEAN_VERSION=${RAW_VERSION#GIT_VERSION=}
          echo "VERSION=$CLEAN_VERSION" >> $GITHUB_OUTPUT

      - name: Package
        run: |
          PKG_NAME="git-macos-${{ steps.get_version.outputs.VERSION }}"
          mv $HOME/git-portable $HOME/$PKG_NAME
          cd $HOME
          tar -czvf $PKG_NAME.tar.gz $PKG_NAME
          cp $PKG_NAME.tar.gz $GITHUB_WORKSPACE/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ steps.get_version.outputs.VERSION }}
          tag_name: v${{ steps.get_version.outputs.VERSION }}-${{ github.run_number }}
          files: /Users/runner/git-macos-${{ steps.get_version.outputs.VERSION }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
